### ISSUE TITLE
KeyboardType is checking for the wrong values

### ISSUE THREAD

**Issue by leolobato** [kareman/mySettings#1]
-setConfiguration: on TextfieldCell.m is checking for the wrong values on the plist file for keyboardType.

For example, it's expecting @"UIKeyboardTypeNumberPad" where standard Apple's plist format would have @"NumberPad".

**Comment by kareman** [comment]
Thanks, I've fixed it. 

These are the values it handles now:
Alphabet
NumbersAndPunctuation
URL
NumberPad
PhonePad
NamePhonePad
EmailAddress
